apiVersion: v1
data:
  alertmanager.yaml: Imdsb2JhbCI6IAogICJyZXNvbHZlX3RpbWVvdXQiOiAiNW0iCiJyZWNlaXZlcnMiOgotICJuYW1lIjogInNsYWNrX2FsZXJ0MSIKICAic2xhY2tfY29uZmlncyI6CiAgLSAiYXBpX3VybCI6ICJodHRwczovL2hvb2tzLnNsYWNrLmNvbS9zZXJ2aWNlcy9USFNCM0ozSzYvQkhUSEgxR01EL2NoMWZsTXhCMERCZURBNk9CNzJzd2FRQSIKICAgICJjaGFubmVsIjogIiNhbGVydF8xIgotICJuYW1lIjogInNsYWNrX2FsZXJ0MiIKICAic2xhY2tfY29uZmlncyI6CiAgLSAiYXBpX3VybCI6ICJodHRwczovL2hvb2tzLnNsYWNrLmNvbS9zZXJ2aWNlcy9USFNCM0ozSzYvQkhUSEgxR01EL2NoMWZsTXhCMERCZURBNk9CNzJzd2FRQSIKICAgICJjaGFubmVsIjogIiNhbGVydF8yIgoicm91dGUiOiAKICAiZ3JvdXBfYnkiOiAKICAtICJqb2IiCiAgImdyb3VwX2ludGVydmFsIjogIjFtIgogICJncm91cF93YWl0IjogIjMwcyIKICAicmVjZWl2ZXIiOiAic2xhY2tfYWxlcnQxIgogICJyZXBlYXRfaW50ZXJ2YWwiOiAiM20iCiAgInJvdXRlcyI6IAogIC0gIm1hdGNoIjogCiAgICAgICJhbGVydG5hbWUiOiAiV2F0Y2hkb2ciCiAgICAicmVjZWl2ZXIiOiAic2xhY2tfYWxlcnQyIgo=
kind: Secret
metadata:
  name: alertmanager-main
  namespace: monitoring
type: Opaque
