apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: vault
  labels:
    team: sre
spec:
  selector:
    matchLabels:
      app: vault
  endpoints:
  - port: metrics
  - port: statsd